// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class OpenCartAdministrationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void openCartAdministration() {
    driver.get("https://www.opencart.com/");
    driver.manage().window().setSize(new Dimension(1440, 900));
    driver.findElement(By.cssSelector(".nav > li:nth-child(2) > a")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".col-sm-6:nth-child(2) .box-overlay")).click();
    vars.put("win9744", waitForWindow(2000));
    driver.switchTo().window(vars.get("win9744").toString());
    driver.findElement(By.id("input-username")).click();
    driver.findElement(By.id("input-username")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .input-group")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Dashboard")).click();
    driver.findElement(By.linkText("Catalog")).click();
    driver.findElement(By.linkText("Categories")).click();
    driver.findElement(By.linkText("Products")).click();
    driver.findElement(By.linkText("Recurring Profiles")).click();
    driver.findElement(By.linkText("Filters")).click();
    driver.findElement(By.linkText("Attributes")).click();
    driver.findElement(By.cssSelector("#collapse5 > li:nth-child(1) > a")).click();
    driver.findElement(By.linkText("Attribute Groups")).click();
    driver.findElement(By.linkText("Options")).click();
    driver.findElement(By.linkText("Manufacturers")).click();
    driver.findElement(By.linkText("Downloads")).click();
    driver.findElement(By.linkText("Reviews")).click();
    driver.findElement(By.linkText("Information")).click();
    driver.findElement(By.linkText("Extensions")).click();
    driver.findElement(By.linkText("Marketplace")).click();
    driver.findElement(By.id("column-left")).click();
    driver.findElement(By.linkText("Installer")).click();
    driver.findElement(By.cssSelector("#collapse14 > li:nth-child(3) > a")).click();
    driver.findElement(By.linkText("Modifications")).click();
    driver.findElement(By.linkText("Events")).click();
    driver.findElement(By.linkText("Design")).click();
    driver.findElement(By.linkText("Layouts")).click();
    driver.findElement(By.linkText("Customers")).click();
    driver.findElement(By.cssSelector("#collapse33 > li:nth-child(1) > a")).click();
    driver.findElement(By.linkText("Customer Groups")).click();
    driver.findElement(By.linkText("Customer Approvals")).click();
    driver.findElement(By.linkText("Custom Fields")).click();
    driver.findElement(By.linkText("Marketing")).click();
    driver.findElement(By.cssSelector("#collapse38 > li:nth-child(1) > a")).click();
    driver.findElement(By.linkText("Coupons")).click();
    driver.findElement(By.linkText("Mail")).click();
    driver.findElement(By.linkText("System")).click();
    driver.findElement(By.linkText("Settings")).click();
    driver.findElement(By.linkText("Localisation")).click();
    driver.findElement(By.linkText("Store Location")).click();
    driver.findElement(By.linkText("Languages")).click();
    driver.findElement(By.linkText("Currencies")).click();
    driver.findElement(By.linkText("Stock Statuses")).click();
    driver.findElement(By.linkText("Order Statuses")).click();
    driver.findElement(By.linkText("Returns")).click();
    driver.findElement(By.linkText("Return Statuses")).click();
    driver.findElement(By.linkText("Return Actions")).click();
    driver.findElement(By.linkText("Return Reasons")).click();
    driver.findElement(By.cssSelector(".hidden-xs")).click();
  }
}
